# Generated by Django 5.1.7 on 2025-05-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='GeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='ad',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_board.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='general_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_board.generalcategory', verbose_name='Основная категория'),
        ),
    ]
