# Generated by Django 5.1.7 on 2025-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_board', '0002_ad_image_ad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Изображение'),
        ),
    ]
